defaults: &defaults
  summary_file: wiki.json
  data_path: <%= "#{Rails.root}/db/wiki" %>
  image_path: <%= "#{Rails.root}/public/images" %>
  users_conf: users.yml
  users_conf_path: <%= "#{Rails.root}/config" %>

development:
  <<: *defaults

test:
  <<: *defaults
  users_conf_path: <%= "#{Rails.root}/test/config" %>

production:
  <<: *defaults
